---
- name: make a build dir
  file: state=directory name=/root/haproxy-dockerized

- name: put Dockerfile
  template: src=Dockerfile dest=/root/haproxy-dockerized/Dockerfile

- name: put start.sh
  template: src=start.sh dest=/root/haproxy-dockerized/start.sh mode=0755

- name: build a Docker image for HAProxy
  command: docker build -t gitinsky/haproxy:0.1.0 --rm /root/haproxy-dockerized

- name: tag it as latest
  command: docker build -t gitinsky/haproxy:latest --rm /root/haproxy-dockerized
